# CI/CD Pipeline
trigger:
  branches:
    include:
      - '*'

jobs:
- job: Build
  displayName: 'Build and Test'
  pool:
    vmImage: 'windows-latest'
  steps:
  - checkout: self
  - task: UseNode@1
    inputs:
      versionSpec: '14.x'
      addToPath: true
  - script: |
      npm install
      npm run build
    displayName: 'Build'

- deployment: Deploy
  displayName: 'Deploy to Windows Server'
  pool:
    vmImage: 'windows-latest'
  environment: 'YourEnvironmentName'
  strategy:
    runOnce:
      deploy:
        steps:
        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(Build.ArtifactStagingDirectory)'
            Contents: '**'
            TargetFolder: 'C:\pipeline'
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: |
              $uniqueWebsiteName = "IOTUI_$(Build.BuildId)"
              $uniqueAppPoolName = "IOTUI_Pool_$(Build.BuildId)"
              Write-Host "##vso[task.setvariable variable=WebsiteName;isOutput=true]$uniqueWebsiteName"
              Write-Host "##vso[task.setvariable variable=AppPoolName;isOutput=true]$uniqueAppPoolName"
        - task: IISWebAppManage@0
          inputs:
            IISDeploymentType: 'IISWebsite'
            ActionIISWebsite: 'CreateOrUpdateWebsite'
            WebsiteName: '$(IOTUI)'
            PhysicalPath: 'C:\pipeline'
            Port: 80
            AddBinding: true
        - task: IISWebAppPoolManage@0
          inputs:
            IISDeploymentType: 'IISAppPool'
            ActionIISAppPool: 'RecycleAppPool'
            RecyclingAppPool: '$(IOTUI_Pool)'
