trigger:
  - main

variables:
  buildConfiguration: 'Release'
  nodeVersion: '14.x'
  stagingEnvironment: 'Staging'
  productionEnvironment: 'TestProduction'
  appName: 'IoTApplication'

stages:
- stage: Build
  displayName: 'Build and Test'
  jobs:
  - job: Build
    pool:
      vmImage: 'windows-latest'
    steps:
    - checkout: self
      persistCredentials: true

    - task: UseNode@1
      inputs:
        versionSpec: '$(nodeVersion)'
        addToPath: true

    - script: |
        npm install
        npm run build
        npm test
      displayName: 'Install, Build, and Test'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(IoTApplication).zip'
        replaceExistingArchive: true

- stage: Test
  displayName: 'Run Tests'
  jobs:
  - job: Test
    dependsOn: Build
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: UseNode@1
      inputs:
        versionSpec: '$(nodeVersion)'
        addToPath: true

    - checkout: self
      persistCredentials: true

    - script: |
        npm install
        npm test
      displayName: 'Run Tests'

- stage: DeployStaging
  displayName: 'Deploy to Staging'
  jobs:
  - job: DeployStaging
    dependsOn: Test
    pool:
      vmImage: 'windows-latest'
    steps:
    - download: current
      artifact: 'YourAppName'

    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'IBIoT'
        appName: '$(appName)-$(stagingEnvironment)'
        package: '$(Pipeline.Workspace)/IoTApplication.zip'
        configurationSettings: 'NODE_ENV=staging'

  # Dummy job with no dependencies
  - job: DummyDeployStaging
    pool:
      vmImage: 'windows-latest'

- stage: DeployProduction
  displayName: 'Deploy to Production'
  jobs:
  - job: DeployProduction
    dependsOn: DeployStaging
    pool:
      vmImage: 'windows-latest'
    steps:
    - download: current
      artifact: 'IoTApplication'

    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'IBIoT'
        appName: '$(appName)-$(productionEnvironment)'
        package: '$(Pipeline.Workspace)/IoTApplication.zip'
        configurationSettings: 'NODE_ENV=production'

  # Dummy job with no dependencies
  - job: DummyDeployProduction
    pool:
      vmImage: 'windows-latest'
