trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildConfiguration: 'Release'
  webAppName: 'IoTUI'
  iisSiteName: 'IoTUI'
  serverAddress: '98.70.42.23'
  username: 'IBuser'
  password: 'IBtesting#321'

stages:
- stage: Build
  displayName: 'Build and Publish'
  jobs:
  - job: Build
    displayName: 'Build'
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK'
      inputs:
        version: '3.x'
        includePreviewVersions: true

    - task: DotNetCoreCLI@2
      displayName: 'Restore and Build'
      inputs:
        command: 'restore'
        projects: '$(solution)'

    - task: DotNetCoreCLI@2
      displayName: 'Publish'
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'drop'
        publishLocation: 'Container'

- stage: Deploy
  displayName: 'Deploy to IIS'
  jobs:
  - job: Deploy
    displayName: 'Deploy'
    environment: 'Sampleproduction'
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: DownloadBuildArtifacts@0
      displayName: 'Download Build Artifacts'
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'

    - task: IISWebAppManagementOnMachineGroup@0
      displayName: 'Stop IIS App Pool'
      inputs:
        IISDeploymentType: 'IISApplicationPool'
        ActionIISApplicationPool: 'Stop'
        StartStopRecycleAppPoolName: '$(IoTUI)'
        StartupType: 'Automatic'

    - task: IISWebAppDeploymentOnMachineGroup@0
      displayName: 'Deploy to IIS'
      inputs:
        WebSiteName: '$(IoTUI)'
        VirtualApplication: '/'
        Package: '$(System.ArtifactsDirectory)\drop\IoTUI.zip'
        RemoveAdditionalFilesFlag: true

    - task: IISWebAppManagementOnMachineGroup@0
      displayName: 'Start IIS App Pool'
      inputs:
        IISDeploymentType: 'IISApplicationPool'
        ActionIISApplicationPool: 'Start'
        StartStopRecycleAppPoolName: '$(IoTUI)'
        StartupType: 'Automatic'
