trigger:
- main

pool:
  name: 'windows-agent'

steps:
- script: |
    node --version  # Check installed Node.js version
    ng --version    # Check installed Angular version
  displayName: 'Check Node.js and Angular versions'

- script: |
    npm install    # Install project dependencies
    npm run build  # Build the Angular project
  displayName: 'npm install and build'
  
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/build'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(uiName).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'container'
