trigger:
- master  

pool:
  vmImage: 'windows-latest'  

variables:
  solution: '**/*.sln'  
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build
    displayName: 'Build Job'
    steps:
    - task: NuGetToolInstaller@1
      displayName: 'Use NuGet 5.x'
      inputs:
        versionSpec: '5.x'
        checkLatest: true

    - task: NuGetCommand@2
      displayName: 'Restore NuGet Packages'
      inputs:
        command: 'restore'
        restoreSolution: '$(solution)'

    - task: MSBuild@1
      displayName: 'Build Solution'
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:Configuration=$(buildConfiguration) /p:Platform=$(buildPlatform)'

- stage: Deploy
  displayName: 'Deploy Stage'
  jobs:
  - job: Deploy
    displayName: 'Deploy Job'
    steps:
    - task: IISWebAppManagementOnMachineGroup@0
      displayName: 'Stop IIS App'
      inputs:
        IISDeploymentType: 'IIS'
        ActionIISApp: 'Stop'
        EnableIIS: 'true'
        CreateOrUpdateAppPoolForIIS: true
        IISAppPool: 'IoTtesting'
        IISWebSite: 'IoTtestingUI'

    - task: IISWebAppDeploymentOnMachineGroup@0
      displayName: 'Deploy to IIS'
      inputs:
        IISDeploymentType: 'IIS'
        ActionIISApp: 'CreateOrUpdate'
        EnableIIS: 'true'
        CreateOrUpdateAppPoolForIIS: true
        IISAppPool: 'IoTtesting'
        IISWebSite: 'IoTtestingUI'
        VirtualPath: '/'
        PhysicalPath: '$(System.DefaultWorkingDirectory)/YourProjectFolder/bin/$(buildConfiguration)'
        Package: '$(System.DefaultWorkingDirectory)/YourProjectFolder/bin/$(buildConfiguration)'

    - task: IISWebAppManagementOnMachineGroup@0
      displayName: 'Start IIS App'
      inputs:
        IISDeploymentType: 'IIS'
        ActionIISApp: 'Start'
        EnableIIS: 'true'
        CreateOrUpdateAppPoolForIIS: true
        IISAppPool: 'IoTtesting'
        IISWebSite: 'IoTtestingUI'
