trigger:
  - main

pool:
  vmImage: 'windows-latest'

steps:
  - task: UseNode@1
    inputs:
      version: '14.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'Install Dependencies'

  - script: |
      npm run build
    displayName: 'Build Application'

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)/dist'
      contents: '**/*'
      targetFolder: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Copy Files to Artifact Staging Directory'

  - task: PublishPipelineArtifact@1
    inputs:
      artifactName: 'dist-artifact'
      targetPath: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Publish Artifact'
