trigger:
- main  

variables:
  uiname: 'IoT'
  uibuild: '$(uisource)/build'

pool:
  name: 'Azure-DevOps'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - checkout: self
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install Node.js'

    - script: 
        npm install -g @angular/cli
        ng build
      displayName: 'BuildFiles'


    - task: ArchiveFiles@2  
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(uiname).zip'  
        replaceExistingArchive: true

    - task: PublishBuildArtifacts@1
      inputs:
       PathtoPublish: '$(Build.ArtifactStagingDirectory)'
       ArtifactName: 'drop'
       publishLocation: 'container'
       
