# azure-pipelines.yml

trigger:
- master  # Set the branch you want to trigger the build and deploy on

pool:
  vmImage: 'windows-latest'  # Use the latest version of Windows

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  webDeployPackage: '$(Build.ArtifactStagingDirectory)\WebApp.zip'
  webAppName: 'YourWebAppName'
  iisWebsiteName: 'YourIISWebsiteName'
  iisPhysicalPath: 'C:\inetpub\wwwroot\YourIISWebsiteName'

jobs:
- job: Build
  displayName: 'Build and Publish'
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '3.1.x'  # Use the appropriate version of .NET SDK
      installationPath: $(Agent.ToolsDirectory)/dotnet
    displayName: 'Install .NET SDK'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '$(solution)'
    displayName: 'Restore NuGet Packages'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '$(solution)'
      arguments: '--configuration $(buildConfiguration)'
    displayName: 'Build the project'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      publishWebProjects: true
      arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: true
    displayName: 'Publish the project'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'
      publishLocation: 'Container'
    displayName: 'Publish Artifact'

- job: Deploy
  displayName: 'Deploy to IIS'
  dependsOn: Build
  pool:
    vmImage: 'windows-latest'

  steps:
  - task: DownloadPipelineArtifact@2
    inputs:
      buildType: 'current'
      artifactName: 'drop'
      targetPath: '$(System.ArtifactsDirectory)'

  - task: IISWebAppManagementOnMachineGroup@0
    inputs:
      IISDeploymentType: 'IISWebsite'  # Change to 'IISWebApp' if deploying to a virtual directory
      ActionIISWebsite: 'CreateOrUpdateWebsite'
      WebsiteName: '$(iisWebsiteName)'
      WebsitePhysicalPath: '$(iisPhysicalPath)'
      AddBinding: true
      CreateOrUpdateAppPoolForWebsite: true
      AppPoolNameForWebsite: 'YourAppPoolName'
    displayName: 'Create or Update IIS Website'

  - task: IISWebAppManagementOnMachineGroup@0
    inputs:
      IISDeploymentType: 'IISWebApp'  # Change to 'IISWebsite' if deploying to the root of the site
      ActionIISWebsite: 'StopWebsite'
      WebsiteName: '$(iisWebsiteName)'
    displayName: 'Stop IIS Website'

  - task: IISWebAppManagementOnMachineGroup@0
    inputs:
      IISDeploymentType: 'IISWebApp'  # Change to 'IISWebsite' if deploying to the root of the site
      ActionIISWebsite: 'SwapSlots'
      WebsiteName: '$(iisWebsiteName)'
      SourceSlotName: 'current'
      DestinationSlotName: 'target'
    displayName: 'Swap deployment slots'

  - task: IISWebAppManagementOnMachineGroup@0
    inputs:
      IISDeploymentType: 'IISWebApp'  # Change to 'IISWebsite' if deploying to the root of the site
      ActionIISWebsite: 'StartWebsite'
      WebsiteName: '$(iisWebsiteName)'
    displayName: 'Start IIS Website'
