# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
    mkdir $(Build.ArtifactStagingDirectory)/dist  # Create 'dist' directory in staging directory
    Copy-Item -Path $(System.DefaultWorkingDirectory)\dist\* -Destination $(Build.ArtifactStagingDirectory)\dist -Recurse  # Copy files to 'dist' directory in staging directory
  displayName: 'npm install, build, and create artifact'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'  # Publish 'dist' directory as an artifact
    ArtifactName: 'dist'
    publishLocation: 'Container'
