trigger:
- main  


pool:
  name: 'Azure-DevOps'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - checkout: self
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install Node.js'

    - task: CmdLine@2
      inputs:
       script: 'ng build'


    - task: ArchiveFiles@2  
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory).zip'  
        replaceExistingArchive: true

    - task: PublishBuildArtifacts@1
      inputs:
       PathtoPublish: '$(Build.ArtifactStagingDirectory)'
       ArtifactName: 'custom-build-artifact'
       publishLocation: 'container'
       
