trigger:
- main

stages:
- stage: Build
  jobs:
  - job: BuildJob
    displayName: 'Build Job'
    pool:
      vmImage: 'windows-latest'

    steps:
    - checkout: self

    # Add your build steps here...

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'MyBuildArtifacts'
        publishLocation: 'Container'

- stage: Deploy
  jobs:
  - job: DeployJob
    displayName: 'Deploy Job'
    pool:
      vmImage: 'windows-latest'

    steps:
    - checkout: self

    # Add your deployment steps here...

    # Use the published artifact from the build stage
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'MyBuildArtifacts'
        downloadPath: '$(System.ArtifactsDirectory)'

- stage: Deploy
  jobs:
  - job: Deploy
    displayName: 'Deploy Job'
    dependsOn: Build
    steps:
    - checkout: self

    - task: IISWebAppManagementOnMachineGroup@0
      inputs:
        IISDeploymentType: 'IISWebsite'
        ActionIISWebsiteCreateOrUpdate: 'CreateOrUpdateWebsite'
        WebsiteName: 'IoTApplication'
        PhysicalPath: '$(System.ArtifactsDirectory)\MyBuildArtifacts' # Adjust the path to your artifacts
        Port: '80'
        CreateOrUpdateAppPool: true
        AppPoolName: 'IoT_pool'
        DotNetVersion: 'v4.0'

    - task: IISWebAppDeploymentOnMachineGroup@0
      inputs:
        WebSiteName: 'IoTApplication'
        VirtualApplication: '/'
        Package: '$(System.ArtifactsDirectory)\MyBuildArtifacts' # Adjust the path to your artifacts
        RemoveAdditionalFilesFlag: true
