trigger:
  - main

pool:
  vmImage: 'windows-latest'

jobs:
  - job: Build
    displayName: 'Build and Test'
    steps:
      - checkout: self
        persistCredentials: true

      - task: UseNode@1
        inputs:
          versionSpec: '14.17.5'
          addToPath: true

      - script: |
          npm install
          npm run build
          npm test
        displayName: 'Install, Build, and Test'

      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
          includeRootFolder: false
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/node-app.zip'
          replaceExistingArchive: true

  - job: Test
    displayName: 'Run Tests'
    dependsOn: Build
    steps:
      - task: UseNode@1
        inputs:
          versionSpec: '14.17.5'
          addToPath: true

      - checkout: self
        persistCredentials: true

      - script: |
          npm install
          npm test
        displayName: 'Run Tests'
