trigger:
- main  

pool:
  vmImage: 'windows-latest'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - checkout: self
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'  # Specify the Node.js version
      displayName: 'Install Node.js'
    - script: |
        npm install
        npm run build  # Execute your build command here
      displayName: 'Build Node.js App'
- task: CopyFiles@2
  inputs:
    Contents: '**/*.js'
    TargetFolder: 'dist'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'dist'
    publishLocation: 'Container'