trigger:
  - main

pool:
  vmImage: 'windows-latest'

- task: Cache@2
  inputs:
    key: 'npm | "$(Agent.OS)" | package-lock.json'
    path: '$(npm_config_cache)'
    cacheHitVar: 'npmCacheRestored'
  displayName: 'Cache npm modules'

steps:
  - task: UseNode@1
    inputs:
      version: '14.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'Install Dependencies'

  - script: |
      npm run build
    displayName: 'Build Application'

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)/dist'
      contents: '**/*'
      targetFolder: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Copy Files to Artifact Staging Directory'

  - task: PublishPipelineArtifact@1
    inputs:
      artifactName: 'dist-artifact'
      targetPath: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Publish Artifact'
