trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: 'Build and Publish'
  jobs:
  - job: Build
    displayName: 'Build'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build
      displayName: 'Install and Build'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        pathtoPublish: '$(System.DefaultWorkingDirectory)'
        artifactName: 'drop'
        publishLocation: 'Container'
        trigger: none  # No trigger for the CD pipeline, as it is manually triggered after CI

pool:
  vmImage: 'windows-latest'

variables:
  webAppName: 'Ideabytes'
  iisSiteName: 'Ideabytes.iotui.com'
  serverAddress: '98.70.42.23'
  username: 'IBuser'
  password: 'IBtesting#321'

stages:
- stage: Deploy
  displayName: 'Deploy to IIS'
  jobs:
  - job: Deploy
    displayName: 'Deploy'
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: DownloadBuildArtifacts@0
      displayName: 'Download Build Artifacts'
      inputs:
        buildType: 'specific'
        project: 'IdeabytesCICD'  # Replace with your Azure DevOps project name
        pipeline: 'DurgaprasadIB.ClientUIForAzure'  # Replace with your CI pipeline name
        runVersion: '20231124.4'  # Replace with your specific CI pipeline run number or tag
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'

    - task: IISWebAppDeploymentOnMachineGroup@0
      displayName: 'Deploy to IIS'
      inputs:
        WebSiteName: '$(Ideabytes.iotui.com)'
        VirtualApplication: '/C:/pipeline'
        Package: '$(System.ArtifactsDirectory)/drop'
        RemoveAdditionalFilesFlag: true

    - task: IISWebAppManagementOnMachineGroup@0
      displayName: 'Stop IIS App Pool'
      inputs:
        IISDeploymentType: 'Ideabytes.iotui.com'
        ActionIISApplicationPool: 'Stop'
        StartStopRecycleAppPoolName: '$(Ideabytes.iotui.com)'
        StartupType: 'Automatic'

    - task: IISWebAppManagementOnMachineGroup@0
      displayName: 'Start IIS App Pool'
      inputs:
        IISDeploymentType: 'Ideabytes.iotui.com'
        ActionIISApplicationPool: 'Start'
        StartStopRecycleAppPoolName: '$(Ideabytes.iotui.com)'
        StartupType: 'Automatic'

