trigger:
- main  # or the branch you want to trigger on

pool:
  vmImage: 'windows-latest'

jobs:
- job: Build
  displayName: 'Build Job'
  steps:
  - checkout: self

  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'Build Node.js App'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifacts'
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)\C:\pipeline'
      ArtifactName: 'drop'
      publishLocation: 'Container'

- job: Deploy
  displayName: 'Deploy Job'
  dependsOn: Build

  steps:
  - checkout: self

  - task: DownloadBuildArtifacts@0
    displayName: 'Download Artifacts'
    inputs:
      buildType: 'current'
      downloadType: 'single'
      artifactName: 'drop'
      downloadPath: '$(System.DefaultWorkingDirectory)\C:\pipeline'

  - task: IISWebAppManagementOnMachineGroup@0
    inputs:
      IISDeploymentType: 'IISWebsite'  # or 'IISWebApp'
      ActionIISWebsiteCreateOrUpdate: 'CreateOrUpdateWebsite'
      WebsiteName: 'IoTApplication'
      PhysicalPath: '$(System.DefaultWorkingDirectory)\C:\pipeline'
      Port: '80'  # or your desired port
      CreateOrUpdateAppPool: true
      AppPoolName: 'IoT_pool'
      DotNetVersion: 'v4.0'  # or your desired .NET version

  - task: IISWebAppDeploymentOnMachineGroup@0
    inputs:
      WebSiteName: 'IoTApplication'
      VirtualApplication: '/'  # or your virtual path
      Package: '$(System.DefaultWorkingDirectory)\C:\pipeline'
      RemoveAdditionalFilesFlag: true
