trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build
  displayName: 'Build Node.js App'
  steps:
  - checkout: self
    fetchDepth: 2

  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build  # Assuming your build script generates the 'dist' folder
    displayName: 'Install Dependencies and Build'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(System.DefaultWorkingDirectory)/dist'
      artifactName: 'dist'
    displayName: 'Publish Build Artifacts'

- job: Deploy
  displayName: 'Deploy to Azure Windows VM IIS Server'
  dependsOn: Build
  pool:
    vmImage: 'windows-latest'
  steps:
  - download: current
    artifact: 'dist'

  - task: IISWebAppManagementOnMachineGroup@0
    inputs:
      IISDeploymentType: 'IISWebsite'
      ActionIISWebsite: 'IoTTesting'
      WebsiteName: 'YourWebsiteName'
      WebsitePhysicalPath: '$(System.ArtifactsDirectory)/dist'
      AddBinding: true
      CreateOrUpdateAppPoolForWebsite: true
      AppPoolNameForWebsite: 'IoTTesting_Pool'
      DotNetVersionForAppPool: 'v4.0'

  - task: IISWebAppDeploymentOnMachineGroup@0
    inputs:
      WebSiteName: 'IoTTesting'
      VirtualApplication: '/'
      Package: '$(System.ArtifactsDirectory)/dist'
      RemoveAdditionalFilesFlag: true