trigger:
- main

pool:
  vmImage: 'windows-latest'  # Change to Windows-latest

jobs:
- job: Build
  steps:
  - task: UseNode@2  # Use the UseNode task to set up Node.js on a Windows agent
    inputs:
      version: '14.x'
      checkLatest: true

  - script: |
      # Your build commands here
      npm install
      npm run build
      ng build --prod

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)/path/to/dist'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/dist'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/dist'
      ArtifactName: 'dist'
      publishLocation: 'Container'
