trigger:
- main
#- dev

pool:
  vmImage: 'windows-latest'

jobs:
  - job: 'Dev_build'
    #condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
    steps :
   # - task: UseNode@1
      #inputs:
    #    versionSpec: '18.x'
     #   displayname: 'Insatll Node.js'
  - task: NodeTool@0
    inputs:
      versionSource: 'spec'
      versionSpec: '18.X'
      checkLatest: true

    - script: |
        npm install -g @angular/cli
        npm install

    - script:    
        ng build --congfiguration test
      displayName: 'npm install and build'

# Used to diagnostic the file structure
#   - task: Bash@3
#     inputs:
#      targetType: 'inline'
#      script: 'find -name node_modules -prune -o -print'

    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '''**dist/Ibsmart*'''
        TargetFolder: '$(Build.ArtifactStagingDirectory)/'
      displayName: 'Copy Files to Artifact Staging Directory'
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Artifact' 
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'www'
 

