trigger:
- main

pr:
- main

pool:
  vmImage: 'windows-latest'

stages:
- stage: Build
  jobs:
  - job: Build
    displayName: 'Build and Publish Artifact'
    steps:
    - checkout: self
    - task: UseNode@1
      inputs:
        versionSpec: '14.x'
        addToPath: true
    - script: |
        npm install
        ng build
      displayName: 'Build Node.js App'
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: 'dist'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/'
      displayName: 'Copy Files to Artifact Staging Directory'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'nodejs_artifact'
      displayName: 'Publish Artifact'

- stage: Deploy
  jobs:
  - deployment: Deploy
    displayName: 'Deploy to IIS'
    environment: 'DEV'
    pool:
      vmImage: 'windows-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: 'nodejs_artifact'
            
          - script: 'C:\Windows\system32\inetsrv\appcmd.exe delete site "default web site"'
            displayName: 'Remove Default Web Site'
          - task: IISWebAppManagementOnMachineGroup@0
            inputs:
              IISDeploymentType: 'IISWebsite'
              ActionIISWebsite: 'CreateOrUpdateWebsite'
              WebsiteName: 'IoTTesting'
              PhysicalPath: '$(System.DefaultWorkingDirectory)/dist'
              Port: '443'
              AddBinding: true
              AppPoolName: 'IoTTesting_Pool'
              AppPoolIdentity: 'NetworkService'
          - task: IISWebAppDeploymentOnMachineGroup@0
            inputs:
              WebSiteName: 'IoTTesting'
              VirtualPath: '/'
              Package: '$(System.DefaultWorkingDirectory)/dist'
              XmlVariableSubstitution: true
