trigger:
- main  

pool:
  vmImage: 'windows-latest'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - checkout: self
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'  # Specify the Node.js version
      displayName: 'Install Node.js'
    - script: |
        npm install
        npm run build  # Execute your build command here
      displayName: 'Build Node.js App'
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/*.js'  # Adjust the pattern based on your project structure
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
      displayName: 'Copy Dist Files'

- stage: Deploy
  jobs:
  - deployment: DeployJob
    environment: 'DEV'  # Replace with your environment name
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(System.ArtifactsDirectory).dist'
              ArtifactName: 'dist'
              publishLocation: 'Container'
            displayName: 'Publish Artifact'
          - task: CopyFiles@2  # [2](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/copy-files-v2?view=azure-pipelines)
            inputs:
              SourceFolder: '$(Pipeline.Workspace).dist'
              Contents: '**'
              TargetFolder: '$(System.ArtifactsDirectory).dist'
            displayName: 'Copy Dist to Artifact Staging'

- stage: IISSetup
  jobs:
  - job: IISSetupJob
    pool:
      vmImage: 'windows-latest'
    steps:
    - checkout: self
    - task: IISWebAppManagementOnMachineGroup@0
      inputs:
        ActionIIS: 'CreateOrUpdateWebsite'
        WebsiteName: 'IoTUI'  # Replace with your desired website name
        PhysicalPath: '$(System.ArtifactsDirectory).dist'  # Replace with the artifact path
        Bindings: 'localhost:80'  # Adjust the port and hostname
        StartWebsite: true
      displayName: 'Create or Update Website'

