# CI/CD Pipeline
trigger:
  branches:
    include:
      - '*'

jobs:
- job: Build
  displayName: 'Build and Test'
  pool:
    vmImage: 'windows-latest'
  steps:
  - checkout: self
  - task: UseNode@1
    inputs:
      versionSpec: '14.x'
      addToPath: true
  - script: |
      npm install
      npm run build
    displayName: 'Build'
  - task: CopyFiles@2
    inputs:
      SourceFolder: 'src'  # Update this to the actual source folder
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Copy Files'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'
    displayName: 'Publish Artifacts'

- deployment: Deploy
  displayName: 'Deploy to Windows Server'
  pool:
    vmImage: 'windows-latest'
  environment: 'YourEnvironmentName'
  strategy:
    runOnce:
      deploy:
        steps:
        - task: DownloadBuildArtifacts@0
          inputs:
            artifactName: 'drop'
            downloadPath: '$(Build.ArtifactStagingDirectory)'
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: |
              $uniqueWebsiteName = "IOTUI_$(Build.BuildId)"
              $uniqueAppPoolName = "IOTUI_Pool_$(Build.BuildId)"
              Write-Host "##vso[task.setvariable variable=WebsiteName;isOutput=true]$uniqueWebsiteName"
              Write-Host "##vso[task.setvariable variable=AppPoolName;isOutput=true]$uniqueAppPoolName"
        - task: IISWebAppDeploymentOnMachineGroup@0
          inputs:
            WebSiteName: '$(IOTUI)'
            VirtualApplication: ''
            Package: '$(Build.ArtifactStagingDirectory)'
            SetParametersFile: ''
            TakeAppOfflineFlag: 'True'
            XmlTransformation: 'True'
            XmlVariableSubstitution: 'True'
            RemoveAdditionalFilesFlag: 'True'
            ExcludeFilesFromAppDataFlag: 'False'
            AdditionalArguments: '-UseCheckSum'
            PowerShellVersion: 'LatestVersion'
        - task: IISWebAppDeploymentOnMachineGroup@0
          inputs:
            WebSiteName: '$(IOTUI)'
            ActionIISAppPool: 'RecycleAppPool'
            RecyclingAppPool: '$(IOTUI_Pool)'
