trigger:
  - main

variables:
  buildConfiguration: 'Release'
  nodeVersion: '14.x'
  stagingEnvironment: 'Staging'
  productionEnvironment: 'TestProduction'
  appName: 'IoTApplication'

stages:
- stage: Build
  displayName: 'Build and Test'
  jobs:
  - job: Build
    pool:
      vmImage: 'windows-latest'
    steps:
    - checkout: self
      persistCredentials: true

    - task: UseNode@1
      inputs:
        versionSpec: '$(nodeVersion)'
        addToPath: true

    - script: |
        npm install
        npm run build
        npm test
      displayName: 'Install, Build, and Test'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(appName).zip'
        replaceExistingArchive: true

- stage: DeployStaging
  displayName: 'Deploy to Staging'
  jobs:
  - job: DeployStaging
    pool:
      vmImage: 'windows-latest'
    steps:
    - download: current
      artifact: 'Build'
      patterns: '**/*.zip'

    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'IBIoT'
        appName: '$(appName)-$(stagingEnvironment)'
        package: '$(Pipeline.Workspace)/$(appName).zip'
        configurationSettings: 'NODE_ENV=staging'

# Dummy job with no dependencies for DeployStaging stage
- stage: DeployProduction
  displayName: 'Deploy to Production'
  jobs:
  - job: DeployProduction
    pool:
      vmImage: 'windows-latest'
    steps:
    - download: current
      artifact: 'Build'
      patterns: '**/*.zip'

    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'IBIoT'
        appName: '$(appName)-$(productionEnvironment)'
        package: '$(Pipeline.Workspace)/$(appName).zip'
        configurationSettings: 'NODE_ENV=production'

# Dummy job with no dependencies for DeployProduction stage
- job: DummyJob
  pool:
    vmImage: 'windows-latest'
  displayName: 'Dummy Job'
  steps:
  - script: echo This is a dummy job
    displayName: 'Run Dummy Job'
