trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'production'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'Install Node Packages'

- script: npm run build -- --configuration $(buildConfiguration)
  displayName: 'Build Angular App'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/dist'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/dist'
    flattenFolders: true
  displayName: 'Copy Build Artifacts'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/dist'
    ArtifactName: 'dist'
    publishLocation: 'Container'
  displayName: 'Publish Artifact'

- task: IISWebAppDeploymentOnMachineGroup@0
  inputs:
    WebSiteName: 'IoTtestingUI'  # Replace with your IIS website name
    Package: '$(Build.ArtifactStagingDirectory)/dist'
    XmlTransformation: true
    RemoveAdditionalFilesFlag: true
