trigger:
- main

pr:
- none

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  webAppName: 'IOTUI'
  serverAddress: '98.70.42.23'
  username: 'IBuser'
  password: 'IBtesting#321'

stages:
- stage: Build
  displayName: 'Build and Publish'
  jobs:
  - job: Build
    displayName: 'Build'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build
      displayName: 'Install and Build'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        pathtoPublish: '$(System.DefaultWorkingDirectory)'
        artifactName: 'drop'
        publishLocation: 'Container'

- stage: Deploy
  displayName: 'Deploy to Windows Server'
  jobs:
  - job: Deploy
    displayName: 'Deploy'
    pool:
      vmImage: 'windows-latest'
    environment: 'deployment'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              artifactName: 'drop'
              downloadPath: '$(Build.ArtifactStagingDirectory)'
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                $uniqueWebsiteName = "IOTUI_$(Build.BuildId)"
                $uniqueAppPoolName = "IOTUI_Pool_$(Build.BuildId)"
                Write-Host "##vso[task.setvariable variable=WebsiteName;isOutput=true]$uniqueWebsiteName"
                Write-Host "##vso[task.setvariable variable=AppPoolName;isOutput=true]$uniqueAppPoolName"
          - task: IISWebAppDeploymentOnMachineGroup@0
            inputs:
              WebSiteName: '$(IOTUI)'
              VirtualApplication: ''
              Package: '$(Build.ArtifactStagingDirectory)'
              SetParametersFile: ''
              TakeAppOfflineFlag: 'True'
              XmlTransformation: 'True'
              XmlVariableSubstitution: 'True'
              RemoveAdditionalFilesFlag: 'True'
              ExcludeFilesFromAppDataFlag: 'False'
              AdditionalArguments: '-UseCheckSum'
              PowerShellVersion: 'LatestVersion'
          - task: IISWebAppDeploymentOnMachineGroup@0
            inputs:
              WebSiteName: '$(IOTUI)'
              ActionIISAppPool: 'RecycleAppPool'
              RecyclingAppPool: '$(IOTUI_Pool)'
