trigger:
- main  

pool:
  name: 'Azure-DevOps'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - checkout: self
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install Node.js'
    - script: |
        npm run build 
      displayName: 'Build Node.js App'


    - task: ArchiveFiles@2  # Corrected task name
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/build'
        includeRootFolder: false
        archiveType: 'zip'  # Changed archiveType to 'zip' for Windows
        archiveFile: '$(Build.ArtifactStagingDirectory)/$.zip'  
        replaceExistingArchive: true

    - task: PublishBuildArtifacts@1
      inputs:
       PathtoPublish: '$(Build.ArtifactStagingDirectory)'
       ArtifactName: 'drop'
       publishLocation: 'container'
