trigger:
- main

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build
      displayName: 'Build Node.js Application'

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: 'dist'
        artifactName: 'NodeApp'
      displayName: 'Publish Artifact'

- stage: Deploy
  jobs:
  - job: Deploy
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'specific'
        project: 'IoT'
        pipeline: '<Your_CI_Pipeline_ID>'
        buildVersionToDownload: 'latest'
        downloadType: 'single'
        artifactName: 'NodeApp'
        downloadPath: '$(System.ArtifactsDirectory)'

    - task: IISWebAppManagementOnMachineGroup@0
      inputs:
        IISDeploymentType: 'IISWebsite'
        ActionIISWebsite: 'CreateOrUpdateWebsite'
        WebsiteName: 'IoTUI'
        PhysicalPath: '$(System.ArtifactsDirectory)\NodeApp'
        Port: 80
