trigger:
- main

stages:
- stage: Build
  jobs:
  - job: BuildJob
    displayName: 'Build Job'
    pool:
      vmImage: 'windows-latest'

    steps:
    - checkout: self

    # Add your build steps here...
    # For example, compile code, run tests, etc.

    # Ensure that the output files are placed in the specified directory
    - script: |
        echo "Generating artifacts in $(Build.ArtifactStagingDirectory)"
        # Your build commands here
      displayName: 'Generate Artifacts'

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'MyBuildArtifacts'
        publishLocation: 'Container'

- stage: Deploy
  jobs:
  - job: DeployJob
    displayName: 'Deploy Job'
    pool:
      vmImage: 'windows-latest'

    steps:
    - checkout: self

    # Add your deployment steps here...

    # Use the published artifact from the build stage
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'MyBuildArtifacts'
        downloadPath: '$(System.ArtifactsDirectory)'

  - job: DeployIndependentJob
    displayName: 'Deploy Independent Job'
    dependsOn: []

    steps:
    - checkout: self

    # Add deployment steps with no dependencies here...

    # Use the published artifact from the build stage
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'MyBuildArtifacts'
        downloadPath: '$(System.ArtifactsDirectory)'
