trigger:
- main

pool:
  vmImage: 'windows-latest'

jobs:
- job: Build
  displayName: 'Build and Generate Dist File'
  steps:
  - checkout: self
    fetchDepth: 2

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '3.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - script: |
      dotnet restore
      dotnet build --configuration Release
      dotnet publish ClientPortal.package.json --configuration Release --output $(Build.ArtifactStagingDirectory)/dist
    displayName: 'Build and Publish Dist'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/dist'
      artifactName: 'dist'
    displayName: 'Publish Dist as Build Artifact'

- job: Deploy
  displayName: 'Deploy to Azure Windows VM IIS Server'
  dependsOn: Build
  pool:
    vmImage: 'windows-latest'
  steps:
  - download: current
    artifact: 'dist'

  - task: IISWebAppManagementOnMachineGroup@0
    inputs:
      IISDeploymentType: 'IISWebsite'
      ActionIISWebsite: 'IoTTesting'
      WebsiteName: 'YourWebsiteName'
      WebsitePhysicalPath: '$(System.ArtifactsDirectory)/dist'
      AddBinding: true
      CreateOrUpdateAppPoolForWebsite: true
      AppPoolNameForWebsite: 'IoTTesting_Pool'
      DotNetVersionForAppPool: 'v4.0'

  - task: IISWebAppDeploymentOnMachineGroup@0
    inputs:
      WebSiteName: 'IoTTesting'
      VirtualApplication: '/'
      Package: '$(System.ArtifactsDirectory)/dist'
      RemoveAdditionalFilesFlag: true
