# CI/CD Pipeline
trigger:
  branches:
    include:
      - '*'

jobs:
- job: Build
  displayName: 'Build and Test'
  pool:
    vmImage: 'windows-latest'
  steps:
  - checkout: self
  - task: UseNode@1
    inputs:
      versionSpec: '14.x'
      addToPath: true
  - script: |
      npm install
      npm run build
    displayName: 'Build'

- job: Deploy
  displayName: 'Deploy to Windows Server'
  dependsOn: Build
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.ArtifactStagingDirectory)'
      Contents: '**'
      TargetFolder: 'C:\pipeline'

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        $uniqueWebsiteName = "IOTUI_$(Build.BuildId)"
        $uniqueAppPoolName = "IOTUI_Pool_$(Build.BuildId)"
        
        # Your custom PowerShell script for IIS deployment
        # Example: Create a new website in IIS
        New-WebApp -Name $uniqueWebsiteName -PhysicalPath 'C:\pipeline' -Port 80

        # Example: Recycle the application pool
        Restart-WebAppPool -Name $uniqueAppPoolName
