trigger:
- main

pr:
- main

pool:
  vmImage: 'windows-latest'

stages:
- stage: Build
  jobs:
  - job: Build
    displayName: 'Build and Publish Artifact'
    steps:
    - checkout: self
    - task: UseNode@1
      inputs:
        versionSpec: '14.x'
        addToPath: true
    - script: |
        npm install
        npm run build
        # Assuming 'npm run build' generates the 'dist' folder
      displayName: 'Build Node.js App'
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: 'dist/**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/dist'
      displayName: 'Copy Files to Artifact Staging Directory'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'nodejs_artifact'
      displayName: 'Publish Artifact'

- stage: Deploy
  jobs:
  - deployment: Deploy
    displayName: 'Deploy to IIS'
    environment: 'YourIISEnvironment'
    pool:
      vmImage: 'windows-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: 'nodejs_artifact'
            path: $(System.DefaultWorkingDirectory)/dist
          - task: IISWebAppManagementOnMachineGroup@0
            inputs:
              IISDeploymentType: 'IISWebsite'
              ActionIISWebsite: 'CreateOrUpdateWebsite'
              WebsiteName: 'IoTUI'
              PhysicalPath: '$(System.DefaultWorkingDirectory)/dist'
              Port: '80'
              AddBinding: true
              AppPoolName: 'YourAppPoolName'
              AppPoolIdentity: 'NetworkService'
          - task: IISWebAppDeploymentOnMachineGroup@0
            inputs:
              WebSiteName: 'IoTUI'
              VirtualPath: '/'
              Package: '$(System.DefaultWorkingDirectory)/dist'
              XmlVariableSubstitution: true
