trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.13'
    checkLatest: true
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli@latest
    npm install
    ng build --prod
  displayName: 'Build Angular App'


- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)/dist'
    contents: '**/*'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy Artifacts'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'angular-app'
    publishLocation: 'Container'
  displayName: 'Publish Artifacts'
