trigger:
- main  

pool:
  name: 'Azure-local'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - checkout: self
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install Node.js'

    - script: 
        ng build
        displayName:'npm build'