trigger:
- main

pool:
  vmImage: 'windows-latest'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - checkout: self
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
        checkLatest: true
      displayName: 'Install Node.js'
    - script: |
        npm install
        npm run build
      displayName: 'Build Node.js App'
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/path/to/dist'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/dist'
      displayName: 'Copy Dist Files'

stages :
- stage: Package
  jobs:
  - job: PackageJob
    dependsOn: Build
    steps:
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)/dist'
        artifactName: 'dist'
        publishLocation: 'Container'
      displayName: 'Publish Artifact'

- stage: Deploy
  jobs:
  - job: DeployJob
    dependsOn: Package
    steps:
    - download: current
      artifact: dist
      displayName: 'Download Artifact'
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Pipeline.Workspace)/dist'
        TargetFolder: '$(System.DefaultWorkingDirectory)/dist'
    - task: IISWebAppManagementOnMachineGroup@0
      inputs:
        Action: 'CreateOrUpdateWebsite'
        WebsiteName: 'YourWebsiteName'
        PhysicalPath: '$(System.DefaultWorkingDirectory)/dist'
        Port: '80'
      displayName: 'Create or Update IIS Website'
