trigger:
- master  

pool:
  vmImage: 'windows-latest'  

variables:
  solution: '**/*.sln'  
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build
    displayName: 'Build Job'
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK'
      inputs:
        version: '3.x'
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - task: DotNetCoreCLI@2
      displayName: 'Restore'
      inputs:
        command: 'restore'
        projects: '$(solution)'

    - task: DotNetCoreCLI@2
      displayName: 'Build'
      inputs:
        command: 'build'
        projects: '$(solution)'
        arguments: '--configuration $(buildConfiguration)'

- stage: Deploy
  displayName: 'Deploy Stage'
  jobs:
  - job: Deploy
    displayName: 'Deploy Job'
    steps:
    - task: IISWebAppManagementOnMachineGroup@0
      displayName: 'Stop IIS App'
      inputs:
        IISDeploymentType: 'IIS'
        ActionIISApp: 'Stop'
        EnableIIS: 'true'
        CreateOrUpdateAppPoolForIIS: true
        IISAppPool: 'IoTtesting'
        IISWebSite: 'IoTtestingUI'

    - task: IISWebAppDeploymentOnMachineGroup@0
      displayName: 'Deploy to IIS'
      inputs:
        IISDeploymentType: 'IIS'
        ActionIISApp: 'CreateOrUpdate'
        EnableIIS: 'true'
        CreateOrUpdateAppPoolForIIS: true
        IISAppPool: 'IoTtesting'
        IISWebSite: 'IoTtestingUI'
        VirtualPath: '/'
        PhysicalPath: '$(System.DefaultWorkingDirectory)/<YourProjectFolder>/bin/$(buildConfiguration)/netcoreapp3.1/publish'
        Package: '$(System.DefaultWorkingDirectory)/<YourProjectFolder>/bin/$(buildConfiguration)/netcoreapp3.1/publish'

    - task: IISWebAppManagementOnMachineGroup@0
      displayName: 'Start IIS App'
      inputs:
        IISDeploymentType: 'IIS'
        ActionIISApp: 'Start'
        EnableIIS: 'true'
        CreateOrUpdateAppPoolForIIS: true
        IISAppPool: 'IoTtesting'
        IISWebSite: 'IoTtestingUI'
