trigger:
- main  

pool:
  vmImage: 'windows-latest'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - checkout: self
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install Node.js'
    - script: |
        npm install
        npm run build  # Execute your build command here
        echo $PATH
      displayName: 'Build Node.js App'
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/*.js'  # Adjust the pattern based on your project structure
        TargetFolder: '$(Build.ArtifactStagingDirectory)/dist'
      displayName: 'Copy Dist Files'
