trigger:
  - main
  # - dev

pool:
  vmImage: 'windows-latest'

jobs:
  - job: 'Dev_build'
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
    steps:
      - task: NodeTool@0
        inputs:
          versionSource: 'spec'
          versionSpec: '18.X'
          checkLatest: true

      - script: |
          npm install -g @angular/cli
          npm install

      - script:    
          ng build  
        displayName: 'npm install and build'
      
