trigger:
- main

pool:
  vmImage: 'windows-latest'

jobs:
- job: Build
  displayName: 'Build and Package'
  steps:
  - checkout: self

  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'

  - script: |
      npm install -g @angular/cli
      npm install
      ng build --prod
    displayName: 'Build Angular App'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)/dist'
      ArtifactName: 'drop'
      publishLocation: 'Container'
    displayName: 'Publish Artifacts'

- job: Deploy
  displayName: 'Deploy to IIS'
  dependsOn: Build
  condition: succeeded()
  steps:
  - checkout: self

  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      downloadType: 'single'
      artifactName: 'drop'
      downloadPath: '$(System.ArtifactsDirectory)'

  # Add your IIS deployment steps here based on the downloaded artifacts
