trigger:
- master

pr:
- '*'

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  angularAppName: 'your-angular-app-name'

steps:
- script: npm install
  displayName: 'Install Dependencies'

- script: npm run build -- --prod
  displayName: 'Build Angular App'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/dist/$(IoTUI)'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/publish'
  displayName: 'Copy Build Artifacts'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/publish'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Build Artifacts'

- task: IISWebAppManagementOnMachineGroup@0
  inputs:
    IISDeploymentType: 'IISWebsite'
    ActionIISWebsite: 'CreateOrUpdateWebsite'
    CreateOrUpdateWebsiteName: 'IoTtesting'
    PhysicalPath: '$(System.DefaultWorkingDirectory)/drop'
    AddBinding: true
    CreateOrUpdateAppPoolForWebsite: true
    AppPoolNameForWebsite: 'IoT'
  displayName: 'Create or Update IIS Website'

- task: IISWebAppDeploymentOnMachineGroup@0
  inputs:
    WebSiteName: 'YourIISWebsiteName'
    VirtualApplication: '/'
    Package: '$(System.DefaultWorkingDirectory)/drop'
    XmlVariableSubstitution: true
    TakeAppOfflineFlag: true
  displayName: 'Deploy to IIS Website'
