trigger:
- main

pr:
- none

pool:
  vmImage: 'windows-latest'

stages:
- stage: Build
  displayName: 'Build and Publish'
  jobs:
  - job: Build
    displayName: 'Build'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build
      displayName: 'Install and Build'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        pathtoPublish: '$(System.DefaultWorkingDirectory)'
        artifactName: 'drop'
        publishLocation: 'Container'

- stage: Deploy
  displayName: 'Deploy to Azure App Service'
  jobs:
  - job: Deploy
    displayName: 'Deploy'
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        artifactName: 'drop'
        downloadPath: '$(Build.ArtifactStagingDirectory)'

    - task: AzureRmWebAppDeployment@4
      displayName: 'Deploy to Azure App Service'
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'IoT'
        appType: 'webApp'
        WebAppName: 'IoTUI'
        packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'
