trigger:
- master

pr:
- '*'

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  angularAppName: 'your-angular-app-name'
  nodeVersion: '14.x'  # Specify the desired Node.js version

steps:
- checkout: self
  displayName: 'Checkout Repository'

- task: NodeTool@0
  inputs:
    versionSpec: '$(nodeVersion)'
  displayName: 'Install Node.js'

- script: |
    cd $(Build.SourcesDirectory)/ClientPortal
    npm install
  displayName: 'Install Dependencies'

- script: npm run build -- --prod
  displayName: 'Build Angular App'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/path/to/your/angular/app/dist/$(IoTangularUI)'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/publish'
  displayName: 'Copy Build Artifacts'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/publish'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Build Artifacts'

- task: IISWebAppManagementOnMachineGroup@0
  inputs:
    IISDeploymentType: 'IISWebsite'
    ActionIISWebsite: 'CreateOrUpdateWebsite'
    CreateOrUpdateWebsiteName: 'YourIISWebsiteName'
    PhysicalPath: '$(System.DefaultWorkingDirectory)/drop'
    AddBinding: true
    CreateOrUpdateAppPoolForWebsite: true
    AppPoolNameForWebsite: 'YourAppPoolName'
  displayName: 'Create or Update IIS Website'

- task: IISWebAppDeploymentOnMachineGroup@0
  inputs:
    WebSiteName: 'YourIISWebsiteName'
    VirtualApplication: '/'
    Package: '$(System.DefaultWorkingDirectory)/drop'
    XmlVariableSubstitution: true
    TakeAppOfflineFlag: true
  displayName: 'Deploy to IIS Website'
